name: Selenium Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm install
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.1
      id: setup-chrome
      with: 
        chrome-version: 120
        install-chromedriver: true
    - run: |
        ${{ steps.setup-chrome.outputs.chrome-path }} --version
        
        
      

    - name: Setup ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        if [ ! -f /usr/bin/chromedriver ]; then sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver; fi

    - name: Install Selenium WebDriver
      run: npm install selenium-webdriver

    - name: Start web server
      run: node server.js &
    
    - name: Run Selenium WebDriver test
      run: node Selenium-tests/test.js
